--total marks innings 1
SELECT INNINGS1.RunsScored + EXTRAINNINGS1.ExtraRuns
FROM INNINGS1 
INNER JOIN EXTRAINNINGS1 ON INNINGS1.Ball_ID = EXTRAINNINGS1.Ball_ID;

--total marks innings 2
SELECT INNINGS2.RunsScored + EXTRAINNINGS2.ExtraRuns
FROM INNINGS2
INNER JOIN EXTRAINNINGS2 ON INNINGS2.Ball_ID = EXTRAINNINGS2.Ball_ID;

--wickets innings 1
SELECT COUNT(Ball_ID) FROM DISMISSALINNINGS1;

--wickets innings 2
SELECT COUNT(Ball_ID) FROM DISMISSALINNINGS2;